### ISSUE TITLE
Code that validates

### ISSUE THREAD

**Issue by pvphaneuf** [IfyAniefuna/xpmd#45]
The metadata webapp currently populates its _taxonomy-id_ input control with the internals of the file _ncbi_taxon_ids.json_ included in this repository.

The following metadata webapp features need to also do so:
- [x] input spreadsheet suggestions: `[,"Enter Experiment Date (YYYY-MM-DD)"],[,'"NCBI Taxonomy ID for Strain, Input one of the following: 413997, 243274, 511145, 511693, 668369, or 679895"'],`
- [x] The input spreadsheet validation `if(variable_file_name_array[1][i] == "taxonomy-id") { ...`

**Comment by IfyAniefuna** [comment]
Create list of taxonomy numbers when web app is opened and use it for every time taxonomy id is needed
