### ISSUE TITLE
Two fields populated into metadata that have the same values

### ISSUE THREAD

**Issue by pvphaneuf** [IfyAniefuna/xpmd#59]
I'm often seeing the value "DNA-seq" associated with fields "read-type" and "data-type".
- [ ] We should use the field name "data-type" only and remove "read-type".
- [ ] Ensure that the "data-type" field is populated by the "Data Type" form field.

**Comment by IfyAniefuna** [comment]
Data type is if DNA-seq/RNA-seq ect. and Read-type is for single and pair end reads.
