### ISSUE TITLE
Sample time is never valid

### ISSUE THREAD

**Issue by pvphaneuf** [IfyAniefuna/xpmd#72]
Attached is a spreadsheet that reproduces this issue.
For now, I've commented out the logic the following logic so that people can still use the metadata to spreadsheet feature:
1) sample-time requirement
2) sample-time validation

[Metadata_spreadsheet.txt](https://github.com/IfyAniefuna/experiment_metadata/files/1763969/Metadata_spreadsheet.txt)

**Comment by IfyAniefuna** [comment]
Someone formatted the input spread sheet to have 2 sample time headers
